name = "GrowthPilot Ai"
client_id = "3a973754197c2089a028abb6469130ca"
application_url = "https://growthpilot.icargos.com"
embedded = true

[access_scopes]
scopes = "read_analytics,read_customers,read_inventory,read_marketing_events,read_orders,read_products,read_reports"

[auth]
redirect_urls = ["https://growthpilotai.com/api/auth/callback", "https://growthpilotai.com/auth/callback"]

[webhooks]
api_version = "2024-01"
